wandb_version: 1

SGK:
  desc: null
  value: 1
_wandb:
  desc: null
  value:
    cli_version: 0.10.22
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.3
    t:
      1:
      - 1
      - 5
      2:
      - 1
      - 5
      4: 3.8.3
      5: 0.10.22
      8:
      - 5
a_e:
  desc: null
  value: 10.0
a_v:
  desc: null
  value: 1.0
att_dropout:
  desc: null
  value: 0.5
b_e:
  desc: null
  value: 1.0
b_v:
  desc: null
  value: 1.0
dataset:
  desc: null
  value: CORA
decay:
  desc: null
  value: 0.0005
dropout:
  desc: null
  value: 0.5
emb_dim:
  desc: null
  value: 64
h:
  desc: null
  value: 0.5
kl:
  desc: null
  value: 0.5
lam1_e:
  desc: null
  value: 5.0
lam1_v:
  desc: null
  value: 1.0
lam2_e:
  desc: null
  value: 0.0001
lam2_v:
  desc: null
  value: 0.001
lr:
  desc: null
  value: 0.01
max_epochs:
  desc: null
  value: 2000
model_name:
  desc: null
  value: GCN
mu_e:
  desc: null
  value: 0.3
mu_v:
  desc: null
  value: 0.7
num:
  desc: null
  value: 2000
num_epochs:
  desc: null
  value: 7000
num_heads:
  desc: null
  value: 8
num_layers:
  desc: null
  value: 2
option_loss:
  desc: null
  value: 0
print:
  desc: null
  value: 50
seed:
  desc: null
  value: 1234
sigma_delta_e:
  desc: null
  value: 0.1
sigma_delta_v:
  desc: null
  value: 0.01
use_seed:
  desc: null
  value: true
wandb:
  desc: null
  value: 1
wandb_name:
  desc: null
  value: ours_real_in_optuna_seed
